# Generated by Django 4.2.1 on 2023-08-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scname', models.CharField(max_length=50)),
                ('Scprinc', models.CharField(max_length=50)),
                ('Scloc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.IntegerField()),
                ('Sname', models.CharField(max_length=30)),
                ('Sage', models.IntegerField()),
                ('Scname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panda', to='app1.school')),
            ],
        ),
    ]
